# Generated by Django 5.2 on 2025-06-20 18:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_brokerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
