# Generated by Django 5.2 on 2025-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_alter_brokerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
