# Generated by Django 5.2.3 on 2025-06-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_alter_contactrequest_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='license_number',
        ),
    ]
