# Generated by Django 5.0 on 2025-09-15 21:43

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('media_type', models.CharField(choices=[('video', 'Видео'), ('photo', 'Фото'), ('file', 'Файл'), ('article', 'Статья')], max_length=10, verbose_name='Тип медиа')),
                ('media_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Медиафайл')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Превью')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый (отображать на главной)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['-created_at'],
            },
        ),
    ]
