# Generated by Django 5.0 on 2025-08-14 14:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый (отображать на главной)'),
        ),
    ]
