# Generated by Django 5.0 on 2025-08-14 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_mediaitem_image_mediaitem_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='main_image',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
