# Generated by Django 5.0 on 2025-08-14 14:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0003_remove_mediaitem_main_image_mediaitem_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='video',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Превью'),
        ),
    ]
