# Generated by Django 5.2.3 on 2025-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
