# Generated by Django 5.2 on 2025-06-20 18:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactrequest_is_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Avatar'),
        ),
    ]
