# Generated by Django 5.2 on 2025-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Определяет, является ли пользователь администратором системы', verbose_name='Администратор'),
        ),
    ]
