# Generated by Django 5.2 on 2025-06-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_first_message_paid',
            field=models.BooleanField(default=True, verbose_name='Требуется оплата за первое сообщение'),
        ),
    ]
