# Generated by Django 5.2 on 2025-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contactrequest_is_first_message_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='first_message_sent',
            field=models.BooleanField(default=False, verbose_name='Первое сообщение отправлено'),
        ),
    ]
