# Generated by Django 5.2 on 2025-06-27 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contactrequest_first_message_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_user', models.ForeignKey(blank=True, help_text='Пользователь, который будет получать вопросы после завершенных чатов', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь поддержки')),
            ],
            options={
                'verbose_name': 'Настройки поддержки',
                'verbose_name_plural': 'Настройки поддержки',
            },
        ),
    ]
