# Generated by Django 5.2.3 on 2025-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_supportsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, help_text='Специализации брокера', to='accounts.specialization', verbose_name='Специализации'),
        ),
    ]
