# Generated by Django 5.2.3 on 2025-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_specialization_remove_user_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specializations',
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=100, verbose_name='Passport Data'),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
