# Generated by Django 5.2.3 on 2025-06-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cloudinary public ID'),
        ),
    ]
