# Generated by Django 5.2.3 on 2025-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useragreement_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragreement',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Загрузить PDF'),
        ),
    ]
