# Generated by Django 5.0 on 2025-09-15 21:43

import cloudinary.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты центра')),
            ],
            options={
                'verbose_name': 'Центр города',
                'verbose_name_plural': 'Центры городов',
            },
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дни)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Премиум размещение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещений',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new_flat', 'Новостройка'), ('resale_flat', 'Вторичка'), ('commercial', 'Нежилое помещение'), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('building', 'Здание'), ('home', 'Дом'), ('warehouse', 'Склад'), ('city', 'Город')], default='home', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Линия метро')),
                ('line_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет линии')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rental', models.CharField(choices=[('no', 'Не арендное'), ('monthly', 'Аренда помесячно'), ('daily', 'Аренда посуточно')], default='no', max_length=10, verbose_name='Тип аренды')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Цена')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Цена за месяц')),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Цена за сутки')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('address', models.TextField(verbose_name='Полный адрес')),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('archived', 'В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячее предложение')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего этажей в доме')),
                ('apartment_type', models.CharField(blank=True, choices=[('studio', 'Студия'), ('apartment', 'Апартаменты'), ('regular', 'Обычная квартира')], max_length=20, null=True, verbose_name='Тип квартиры')),
                ('has_finishing', models.BooleanField(default=False, verbose_name='Отделка')),
                ('delivery_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год сдачи')),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('distance_to_center', models.FloatField(blank=True, null=True, verbose_name='Расстояние до центра (км)')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Дом сдан')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Жилая площадь (м²)')),
                ('total_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Общая площадь (м²)')),
                ('metro_station', models.CharField(blank=True, max_length=100, verbose_name='Станция метро')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Координаты')),
                ('metro_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Координаты метро')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='brokers.brokerprofile', verbose_name='Брокер')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_properties', to=settings.AUTH_USER_MODEL, verbose_name='Застройщик')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
                'ordering': ['order'],
            },
        ),
    ]
