# Generated by Django 5.0 on 2025-07-28 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_metro_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты центра')),
            ],
            options={
                'verbose_name': 'Центр города',
                'verbose_name_plural': 'Центры городов',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
