# Generated by Django 5.2 on 2025-06-20 18:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_listingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
