# Generated by Django 5.0 on 2025-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_citycenter_property_construction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='distance_to_center',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние до центра (км)'),
        ),
    ]
