# Generated by Django 5.2 on 2025-06-20 18:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_main',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image'),
        ),
    ]
