# Generated by Django 5.2 on 2025-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
    ]
