# Generated by Django 5.0 on 2025-07-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_metrostation'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrostation',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Линия метро'),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='line_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет линии'),
        ),
    ]
