# Generated by Django 5.2 on 2025-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_propertyimage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('new_flat', 'Квартира в новостройке'), ('resale_flat', 'Квартира на вторичке'), ('commercial', 'Нежилое помещение'), ('house', 'Загородное жилье')], max_length=100, unique=True, verbose_name='Тип объекта'),
        ),
    ]
