# Generated by Django 5.0 on 2025-07-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_metrostation_line_metrostation_line_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('new_flat', 'Новостройка'), ('resale_flat', 'Вторичка'), ('commercial', 'Нежилое помещение'), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта'),
        ),
    ]
