# Generated by Django 5.2 on 2025-06-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertytype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за сутки (₽)'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='is_rental',
            field=models.CharField(blank=True, choices=[('no', 'Не арендное'), ('monthly', 'Аренда помесячно'), ('daily', 'Аренда посуточно')], default='no', max_length=10, verbose_name='Тип аренды'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за месяц (₽)'),
        ),
    ]
