# Generated by Django 5.2 on 2025-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertytype_daily_price_propertytype_is_rental_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='is_rental',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='monthly_price',
        ),
        migrations.AddField(
            model_name='property',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за сутки'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_rental',
            field=models.CharField(choices=[('no', 'Не арендное'), ('monthly', 'Аренда помесячно'), ('daily', 'Аренда посуточно')], default='no', max_length=10, verbose_name='Тип аренды'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
    ]
