# Generated by Django 5.2 on 2025-06-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_propertytype_daily_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('new_flat', 'Новостройка'), ('resale_flat', 'Вторичка'), ('commercial', 'Нежилые помещения '), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта'),
        ),
    ]
