# Generated by Django 5.2 on 2025-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Цена за сутки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Цена за месяц'),
        ),
    ]
